# Generated by Django 3.2.12 on 2022-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokenAPP', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='tem_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
