# Generated by Django 3.2.12 on 2022-05-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenAPP', '0005_tem_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tem_model',
            new_name='temp_model',
        ),
    ]
