# Generated by Django 3.2.12 on 2022-05-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenAPP', '0006_rename_tem_model_temp_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temp_model',
            new_name='temp_user',
        ),
    ]
